COMPUTED VALUES:
affinity: {}
certManager:
  caCertDuration: 43800h0m0s
  certDuration: 8760h0m0s
  enabled: false
customAnnotations: {}
customLabels: {}
deploymentAnnotations: {}
dnsConfig: {}
env: []
extraArguments: []
extraContainers: []
extraVolumeMounts: []
extraVolumes: []
hostNetwork:
  enabled: false
image:
  pullPolicy: IfNotPresent
  repository: registry.k8s.io/prometheus-adapter/prometheus-adapter
  tag: ""
listenPort: 6443
livenessProbe:
  httpGet:
    path: /healthz
    port: https
    scheme: HTTPS
  initialDelaySeconds: 30
  timeoutSeconds: 5
logLevel: 4
metricsRelistInterval: 1m
namespaceOverride: ""
nodeSelector: {}
podAnnotations: {}
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
  minAvailable: null
podLabels: {}
podSecurityContext:
  fsGroup: 10001
priorityClassName: ""
prometheus:
  path: ""
  port: 9090
  url: http://prometheus.default.svc
psp:
  annotations: {}
  create: false
rbac:
  create: true
  customMetrics:
    resources:
    - '*'
  externalMetrics:
    resources:
    - '*'
  useAuthReaderClusterRole: false
readinessProbe:
  httpGet:
    path: /healthz
    port: https
    scheme: HTTPS
  initialDelaySeconds: 30
  timeoutSeconds: 5
replicas: 1
resources: {}
rules:
  external:
  # Metric 1: CPU usage for chain-2 multiplied by the number of pods
  - seriesQuery: 'container_cpu_usage_seconds_total{namespace="default", pod=~"chain-2-.*"}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      matches: ".*"
      as: "chain2_cpu_quota"
    metricsQuery: |
      sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"chain-2-.*"}[2m])) *100
      /
      sum(kube_pod_container_resource_requests{namespace="default", pod=~"chain-2-.*"})
  # Metric 5: CPU usage for chain-1 multiplied by the number of pods
  - seriesQuery: 'container_cpu_usage_seconds_total{namespace="default", pod=~"chain-1-.*"}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
      matches: ".*"
      as: "chain1_cpu_quota"
    metricsQuery: |
      sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"chain-1-.*"}[2m])) *100
      /
      sum(kube_pod_container_resource_requests{namespace="default", pod=~"chain-1-.*"})
  default: false
  existing: null
  custom: []
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault
service:
  annotations: {}
  ipDualStack:
    enabled: false
    ipFamilies:
    - IPv6
    - IPv4
    ipFamilyPolicy: PreferDualStack
  port: 443
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
startupProbe: {}
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
tls:
  ca: '# Public CA file that signed the APIService'
  certificate: '# Public key of the APIService'
  enable: false
  key: '# Private key of the APIService'
tolerations: []
topologySpreadConstraints: []
