{
 "title": "Davide HPA Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Consumption by Service (Total mcore)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", pod=~\"compose-post.*\"}[5m])) * 1000",
     "legendFormat": "compose-post"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", pod=~\"nginx-thrift.*\"}[5m])) * 1000",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", pod=~\"text-service.*\"}[5m])) * 1000",
     "legendFormat": "text-service"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", pod=~\"user-mention.*\"}[5m])) * 1000",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "Replicas per Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"compose.*\"})\n",
     "legendFormat": "compose-post"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"nginx.*\"})\n",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"text.*\"})\n",
     "legendFormat": "test-service"
    },
    {
     "expr": "count by (app) (kube_pod_info{pod=~\"user-mention.*\"})\n",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "Combined CPU Utilization (65% child, 35% parent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(0.65 * (sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"text.*\"})) + 0.35 * (sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"compose.*\"}))) * 100",
     "legendFormat": "text-service + compose-post"
    },
    {
     "expr": "(0.65 * (sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"user-mention.*\"})) + 0.35 * (sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m])) / sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"text.*\"}))) * 100",
     "legendFormat": "user-mention + text-service"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"text-service-hpa\",namespace=\"socialnetwork\"}",
     "legendFormat": "HPA threshold (text + compose)"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"user-mention-service-hpa\",namespace=\"socialnetwork\"}",
     "legendFormat": "HPA threshold (mention + text)"
    }
   ]
  },
  {
   "title": "CPU Utilization per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"compose.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"compose.*\"}) * 100\n",
     "legendFormat": "compose-post-service"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"nginx.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"nginx.*\"}) * 100\n",
     "legendFormat": "nginx-thrift"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"text.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"text.*\"}) * 100\n",
     "legendFormat": "test-service"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"socialnetwork\", container=~\"user-mention.*\"}[2m]))\n/\nsum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"socialnetwork\", container=~\"user-mention.*\"}) * 100\n",
     "legendFormat": "user-mention-service"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"compose-post-service-hpa\",namespace=\"socialnetwork\"}",
     "legendFormat": "HPA threshold (compose-post)"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"nginx-thrift-hpa\",namespace=\"socialnetwork\"}",
     "legendFormat": "HPA threshold (nginx)"
    }
   ]
  },
  {
   "title": "Network I/O Rate per Service (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"socialnetwork\", pod=~\"compose-post.*\"}[2m]) + rate(container_network_transmit_bytes_total{namespace=\"socialnetwork\", pod=~\"compose-post.*\"}[2m])) / 1024",
     "legendFormat": "compose-post-service"
    },
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"socialnetwork\", pod=~\"text-service.*\"}[2m]) + rate(container_network_transmit_bytes_total{namespace=\"socialnetwork\", pod=~\"text-service.*\"}[2m])) / 1024",
     "legendFormat": "text-service"
    },
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"socialnetwork\", pod=~\"user-mention.*\"}[2m]) + rate(container_network_transmit_bytes_total{namespace=\"socialnetwork\", pod=~\"user-mention.*\"}[2m])) / 1024",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "Memory Usage per Service (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"compose-post.*\"}) / 1024 / 1024",
     "legendFormat": "compose-post"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"text-service.*\"}) / 1024 / 1024",
     "legendFormat": "text-service"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"user-mention.*\"}) / 1024 / 1024",
     "legendFormat": "user-mention-service"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage per Service (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"compose-post.*\"}) / sum (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"socialnetwork\", pod=~\"compose-post.*\"}) * 100",
     "legendFormat": "compose-post"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"text-service.*\"}) / sum (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"socialnetwork\", pod=~\"text-service.*\"}) * 100",
     "legendFormat": "text-service"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"socialnetwork\", pod=~\"user-mention.*\"}) / sum (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"socialnetwork\", pod=~\"user-mention.*\"}) * 100",
     "legendFormat": "user-mention-service"
    }
   ]
  }
 ]
}